version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:$ZOOKEEPER_TAG
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
  kafka:
    image: wurstmeister/kafka:${KAFKA_TAG}
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock